backend:
  name: github
  branch: master
  repo: wellingtoncgs30/wsconstrutordesites

media_folder: static/media
public_folder: /media
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: image, widget: image}
      - { name: date, label: Publish Date, widget: datetime }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }